# Generated by Django 4.2 on 2023-04-30 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.demandtype'),
        ),
    ]
