# Generated by Django 4.2 on 2023-06-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default='2023-05-05'),
            preserve_default=False,
        ),
    ]
