# Generated by Django 4.2 on 2023-05-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoption',
            name='name',
            field=models.CharField(choices=[('eSewa', 'eSewa'), ('Khalti', 'Khalti'), ('fonePay', 'fonePay')], max_length=100),
        ),
    ]
