# Generated by Django 4.2 on 2023-06-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentoption_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.paymentoption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='fine_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rebeat_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
