# Generated by Django 4.2 on 2023-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField()),
                ('bill_year', models.DateField()),
                ('bill_month', models.DateField()),
                ('current_reading', models.FloatField()),
                ('prev_reading', models.FloatField()),
                ('bill_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DemandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
