# Generated by Django 4.2 on 2023-04-30 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_demand'),
        ('bill', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandType',
        ),
    ]
