# Generated by Django 4.2 on 2023-05-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_alter_bill_bill_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_month',
            field=models.CharField(choices=[('2080', '2080'), ('2079', '2079'), ('2078', '2078'), ('2077', '2077'), ('2076', '2076'), ('2075', '2075'), ('2074', '2074'), ('2073', '2073'), ('2072', '2072'), ('2071', '2071'), ('2070', '2070'), ('2069', '2069'), ('2068', '2068'), ('2067', '2067'), ('2066', '2066'), ('2065', '2065'), ('2064', '2064'), ('2063', '2063'), ('2062', '2062'), ('2061', '2061'), ('2060', '2060'), ('2059', '2059')], max_length=12),
        ),
    ]
