# Generated by Django 4.2 on 2023-05-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_alter_bill_bill_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_month',
            field=models.CharField(choices=[('Baisakh', 'Baisakh'), ('Jestha', 'Jestha'), ('Ashar', 'Ashar'), ('Sharawan', 'Sharawan'), ('Bhadra', 'Bhadra'), ('Aswin', 'Aswin'), ('Kartik', 'Kartik'), ('Mansir', 'Mansir'), ('Poush', 'Poush'), ('Magh', 'Magh'), ('Falgun', 'Falgun'), ('Chaitra', 'Chaitra')], max_length=12),
        ),
    ]
