# Generated by Django 4.2 on 2023-04-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_rate', models.FloatField()),
                ('effective_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('demand_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.demandtype')),
            ],
        ),
    ]
