# Generated by Django 4.2 on 2023-05-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0002_demandrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandtype',
            name='description',
            field=models.CharField(choices=[('5 Ampere', '5 Ampere'), ('15 Ampere', '15 Ampere'), ('50 Ampere', '50 Ampere')], max_length=50),
        ),
    ]
